//creates a new option element with the specified text and value 
function mountainDropDown(selectbox,text,value )
{
	var optn = document.createElement("option");
	optn.text = text;
	optn.value = value;
	selectbox.options.add(optn);
}
// populate the drop-down menu with a list of mountains using the for loop

function mountainDropDownList(){
for (var i=0; i < mountainsArray.length;++i){
    mountainDropDown(document.drop_list.mountainDropDown, mountainsArray[i].name);
    }
 
}
//For each item in the mountains array, this function creates a new  element
//  and adds it to the dropdown as an option to choose

function loadData() {
    var down = document.getElementById('mountain');
           for (let i = 0; i < mountainsArray.length; i++) {
               var optn = mountainsArray[i];
               var el = document.createElement("option");
               el.textContent = optn;
               el.value = optn;
               down.appendChild(el);
           }
           down.innerHTML = "Elements Added";
 }

 //Functions we are calling 
mountainDropDownList();
loadData();
displayMountain();

// grabs info from mountain data to be displays on a card 
function mountainTemplate(mountain) {
     return `
       <div class="mountain">
       <img class="mountain-photo" src="images/${mountain.img}">
       <h2 class="mountain-name">${mountain.name} <span class="species">(${mountain.elevation} feet)</span></h2>
       <h4 class="mountain-desc">${mountain.desc} </h4>
       <p>Effort: ${mountain.effort}</p>
       </div>
       
     `};
 

//After mountain is selected from dropdown
// if Mountain name is equal to selected option
// card will populate with all Mounain information 

function displayMountain() {
    let mydropdown = document.getElementById('mountainDropDown');
    let value = mydropdown.value;
    let  selectedOption = mydropdown.options[mydropdown.selectedIndex].text;
    const filteredMountains = mountainsArray.filter(mountain => mountain.name === selectedOption);

    //references elements with Id mountains , 
    //and sets inner HTML to a string generated by the mountainTemplate()
    
    document.getElementById("mountains").innerHTML = `
     ${filteredMountains.map(mountainTemplate).join("")}
     <h1 class="app-title"> Check out this awesome Mountain !</h1>
     
   `;  
        
}   
   
  